"use client";
import React, { useEffect, useState } from "react";
import { Menu, MessageCircle, X } from "lucide-react";
import SilverLotusLogo from "./SilverLotusLogo";

export default function Navbar({ onOpenInquiry }: { onOpenInquiry: (productName?: string) => void }) {
  const [open, setOpen] = useState(false); const [scrolled, setScrolled] = useState(false);
  useEffect(() => { const listener = () => setScrolled(window.scrollY > 10); window.addEventListener("scroll", listener); return () => window.removeEventListener("scroll", listener); }, []);
  const go = (id: string) => { setOpen(false); document.getElementById(id)?.scrollIntoView({ behavior: "smooth" }); };
  return <header className={`fixed inset-x-0 top-0 z-50 border-b transition ${scrolled ? "border-white/10 bg-black/85 backdrop-blur-xl" : "border-transparent bg-transparent"}`}><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-3 sm:px-6 lg:px-8"><button onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })} className="flex items-center gap-3 text-left"><SilverLotusLogo size={45} className="ring-1 ring-white/15" /><span><span className="block font-serif text-xl font-bold tracking-[.14em] text-white">PHOOL</span><span className="block text-[9px] font-bold tracking-[.25em] text-cyan-300">SILVER LEAVES</span></span></button><nav className="hidden items-center gap-8 text-sm font-semibold text-slate-300 md:flex"><button onClick={() => go("products")} className="hover:text-cyan-300">Products</button><button onClick={() => go("purity")} className="hover:text-cyan-300">Purity</button><button onClick={() => go("contact")} className="hover:text-cyan-300">Contact</button></nav><button onClick={() => onOpenInquiry()} className="hidden items-center gap-2 rounded-full bg-cyan-300 px-4 py-2 text-xs font-black text-black transition hover:bg-cyan-200 sm:flex"><MessageCircle className="h-4 w-4" /> Order Quote</button><button className="rounded-lg border border-white/15 p-2 text-white md:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</button></div>{open && <div className="border-t border-white/10 bg-black px-4 pb-5 pt-2 md:hidden"><div className="mx-auto flex max-w-7xl flex-col gap-1 text-sm font-semibold text-slate-300"><button onClick={() => go("products")} className="rounded-lg px-3 py-2 text-left hover:bg-white/10">Products</button><button onClick={() => go("purity")} className="rounded-lg px-3 py-2 text-left hover:bg-white/10">Purity</button><button onClick={() => go("contact")} className="rounded-lg px-3 py-2 text-left hover:bg-white/10">Contact</button><button onClick={() => { setOpen(false); onOpenInquiry(); }} className="mt-2 rounded-lg bg-cyan-300 px-3 py-2 text-left font-bold text-black">Request order quote</button></div></div>}</header>;
}
